import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Project Manager | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      <main>Home</main>

    </div>
  )
}
